apiVersion: apps/v1
kind: Deployment
metadata:
  name: test_cicd_springboot_nkp-deployment
  namespace: testapp
  labels:
    app: test_cicd_springboot_nkp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test_cicd_springboot_nkp
  template:
    metadata:
      labels:
        app: test_cicd_springboot_nkp
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
      containers:
        - name: test_cicd_springboot_nkp
          image: 172.20.0.89/univh2ctest-ci-cd/test_cicd_springboot_nkp:11
          ports:
            - containerPort: 7061          
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-html
  namespace: testapp
data:
  index.html: |
    <html>
    <head><title>Hello from Apache in Kubernetes</title></head>
    <body>
      <h1>Welcome to Apache HTTP Server running in Kubernetes, Port 80 !</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: test_cicd_springboot_nkp-service
  namespace: testapp
spec:
  type: LoadBalancer
  selector:
    app: test_cicd_springboot_nkp
  ports:
    - protocol: TCP
      port: 7061
      targetPort: 7061
