apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: testapp
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
      containers:
        - name: httpd
          image: 172.20.0.89/univh2ctest-ci-cd/test_cicd_springboot_nkp:11
          ports:
            - containerPort: 8070
          volumeMounts:
            - name: html-volume
              mountPath: /usr/local/apache2/htdocs/
      volumes:
        - name: html-volume
          configMap:
            name: httpd-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-html
  namespace: testapp
data:
  index.html: |
    <html>
    <head><title>Hello from Apache in Kubernetes</title></head>
    <body>
      <h1>Welcome to Apache HTTP Server running in Kubernetes, Port 80 !</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: testapp
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
